name: pdfrx
description: pdfrx is a rich and fast PDF viewer implementation built on the top of PDFium. The plugin supports Android, iOS, Windows, macOS, Linux, and Web.
version: 1.3.1
homepage: https://github.com/espresso3389/pdfrx
repository: https://github.com/espresso3389/pdfrx
issue_tracker: https://github.com/espresso3389/pdfrx/issues
screenshots:
  - description: 'Viewer example on Web'
    path: screenshot.jpg

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

dependencies:
  collection:
  crypto: ^3.0.6
  ffi:
  flutter:
    sdk: flutter
  http:
  path:
  path_provider: ^2.1.5
  rxdart:
  synchronized: ^3.3.1
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  web: ^1.1.1
  dart_pubspec_licenses: ^3.0.4

dev_dependencies:
  ffigen: ^18.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  archive: ^4.0.2

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
        sharedDarwinSource: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
        sharedDarwinSource: true
      windows:
        ffiPlugin: true
      web:

  assets:
    - assets/

# To generate the bindings, firstly you must build example/viewer on x64 linux and
# then run the following command:
# dart run ffigen
ffigen:
  output:
    bindings: "lib/src/pdfium/pdfium_bindings.dart"
  headers:
    entry-points:
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdfview.h"
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdf_annot.h"
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdf_text.h"
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdf_doc.h"
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdf_edit.h"
      - "example/viewer/build/linux/x64/release/.lib/latest/include/fpdf_formfill.h"
    include-directives:
      - "example/viewer/build/linux/x64/release/.lib/latest/include/**"
  preamble: |
    // ignore_for_file: unused_field
    // dart format off
  name: "pdfium"
  comments:
    style: any
    length: full

